Repository UKHomeOffice/core-cloud-dynatrace-environment-terraform, pull requests merged in 2025-04, with the labels that each got.

#46 CCL-2255: Updating to latest version
  main.tf
Labels: minor

#47 Ccl 2359
  dashboards/ghes_dashboards/main.tf
Labels: patch

#48 CCL-2413 added a value to tags for all golden dashboards
  dashboards/golden_dashboards/cloudfront.tf
  dashboards/golden_dashboards/dynamodb.tf
  dashboards/golden_dashboards/elasticache.tf
  dashboards/golden_dashboards/elasticsearch.tf
  dashboards/golden_dashboards/s3.tf
Labels: patch

#49 CCL-2618 additional variable to determine whether run on SaaS or on-prem
  aws_account_configuration/locals.tf
  aws_account_configuration/main.tf
  aws_account_configuration/variables.tf
Labels: patch

#50 CCL-2405 - Adding component catalog yaml file
  catalog-info.yaml
Labels: patch

#52 Ccl-2618 added saas_metricpolling variables for dynatrace_infrastructure
  aws_account_configuration/main.tf
Labels: patch

#53 CCL-2336: adding templating + dynamic filter
  dashboards/golden_dashboards/dynamodb.tf
  dashboards/golden_dashboards/dynamodb/conditionalcheckfailedrequests.json
  dashboards/golden_dashboards/dynamodb/consumedreadcapacityunits.json
  dashboards/golden_dashboards/dynamodb/consumedwritecapacityunits.json
  dashboards/golden_dashboards/dynamodb/content.tftpl
  dashboards/golden_dashboards/dynamodb/readthrottleevents.json
  dashboards/golden_dashboards/dynamodb/returneditemcount.json
  dashboards/golden_dashboards/dynamodb/successfulrequestlatency.json
  dashboards/golden_dashboards/dynamodb/systemerrors.json
  dashboards/golden_dashboards/dynamodb/throttledrequests.json
  dashboards/golden_dashboards/dynamodb/transactionconflict.json
  dashboards/golden_dashboards/dynamodb/usererrors.json
  dashboards/golden_dashboards/dynamodb/writethrottleevents.json
Labels: enhancement, minor

#55 CCL-2336: adding templating + dynamic filter
  dashboards/golden_dashboards/dynamodb/content.tftpl
Labels: patch

#56 CCL-2336: updating dynamodb filter to amazon one
  dashboards/golden_dashboards/dynamodb/content.tftpl
Labels: minor
