Repository UKHomeOffice/core-cloud-dynatrace-environment-terraform, pull requests merged in 2025-03, with the labels that each got.

#31 Ccl 2185
  dashboards/ghes_dashboards/main.tf
  dashboards/ghes_dashboards/variables.tf
  main.tf
Labels: minor

#32 include missing entity_selector value pass
  dynatrace_management_zones/main.tf
Labels: patch

#33 adding group id variable
  dashboards/ghes_dashboards/main.tf
  dashboards/ghes_dashboards/variables.tf
  main.tf
Labels: minor

#34 Ccl 2185b
  main.tf
Labels: patch

#35 CCL-2235 migrate golden dashboards
  dashboards/golden_dashboards/cloudfront.tf
  dashboards/golden_dashboards/dashboard_variables.tf
  dashboards/golden_dashboards/dynamodb.tf
  dashboards/golden_dashboards/elasticache.tf
  dashboards/golden_dashboards/elasticsearch.tf
  dashboards/golden_dashboards/msk.tf
  dashboards/golden_dashboards/providers.tf
  dashboards/golden_dashboards/rds.tf
  dashboards/golden_dashboards/s3.tf
  main.tf
  variables.tf
Labels: patch

#36 CCL-2235 hardcoded goldendashboard parameter values
  dashboards/golden_dashboards/cloudfront.tf
  dashboards/golden_dashboards/dashboard_variables.tf
  dashboards/golden_dashboards/dynamodb.tf
  dashboards/golden_dashboards/elasticache.tf
  dashboards/golden_dashboards/elasticsearch.tf
  dashboards/golden_dashboards/msk.tf
  dashboards/golden_dashboards/rds.tf
  dashboards/golden_dashboards/s3.tf
  main.tf
  variables.tf
Labels: patch

#37 CCL-2235 corrected a typo
  dashboards/golden_dashboards/rds.tf
Labels: patch

#39 CCL-2255 - Creating resources to manage aws secrets
  main.tf
  variables.tf
Labels: enhancement, minor

#38 remove unnecessary double quotes
  dynatrace_management_zones/main.tf
Labels: patch

#40 remove aws_secret
  variables.tf
Labels: patch

#41 aws_secrets count
  main.tf
Labels: patch

#42 CCL-2255 - Creating resources to manage aws secrets
  main.tf
Labels: patch

#43 CCL-2255 - Creating resources to manage aws secrets
  main.tf
Labels: minor

#44 CCL-2255 - Creating resources to manage aws secrets
  main.tf
Labels: patch

#45 Ccl 2359
  dashboards/ghes_dashboards/main.tf
Labels: minor
