Repository UKHomeOffice/core-cloud-dynatrace-environment-terraform, pull requests merged in 2025-01, with the labels that each got.

#10 adding GHES dashboard code
  dashboards/ghes_dashboard.tf
Labels: minor

#12 CCL-1476: Fixing typo
  alerts/ghes/ghes_alerts.tf
Labels: bug, minor

#14 Ccl 1476
  alerts/ghes/alerts.tf
  alerts/ghes/ghes_alerts.tf
  alerts/ghes/ghes_alerts_variables.tf
  alerts/ghes/ghes_metric_events.tf
  alerts/ghes/main.tf
  alerts/ghes/variables.tf
  alerts/webhook_alert_integration/alerts_profile.tf
  alerts/webhook_alert_integration/providers.tf
  alerts/webhook_alert_integration/variables.tf
  main.tf
Labels: bug, patch

#15 CCL-1476: Moving to main pipeline and refactoring GHES alerts
  alerts/ghes/variables.tf
Labels: bug, minor

#16 CCL-1476: Fixing variable names for GHES alerts
  alerts/ghes/main.tf
  alerts/ghes/variables.tf
Labels: bug, patch

#18 adding ghes dashbaords
  dashboards/ghes_dashboard.tf
  dashboards/ghes_dashboards/main.tf
  dashboards/ghes_dashboards/providers.tf
  dashboards/ghes_dashboards/variables.tf
  main.tf
Labels: minor

#19 CCL-1627 - ghes dashboard in code
  dashboards/ghes_dashboards/main.tf
  dashboards/ghes_dashboards/variables.tf
  main.tf
Labels: patch

#21 CCL-1627 - remove id in ghes dashboard
  dashboards/ghes_dashboards/main.tf
Labels: patch

#22 CCL-1627 - ghes dashboard shared true
  dashboards/ghes_dashboards/main.tf
Labels: patch

#23 CCL-1627 - conditional alerts/dashboards
  main.tf
Labels: patch

#25 CCL-1476: retsricting profiule based on tag
  alerts/ghes/alerts.tf
  alerts/ghes/main.tf
  alerts/ghes/variables.tf
Labels: patch
